COFFEE/Models/CartItem.cs
using Model.EF;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace COFFEE.Models
{
    [Serializable]
    public class CartItem
    {
        public Product Product { set; get; }
        public int Quantity { set; get; }
    }
    
}

COFFEE/Controllers/CartItemController.cs
using COFFEE.Models;
using Model.Dao;
using Model.EF;
using System;
using System.Collections.Generic;
using System.Configuration;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Web.Script.Serialization;
using Common;

namespace COFFEE.Controllers
{
    public class CartItemController : BaseController
    {
        // GET: CartItem
        private const string CartSection = "CartSection";
        // GET: CartItem
        public ActionResult Index()
        {
            var cart = Session[CartSection];
            var list = new List<CartItem>();

            if (cart != null)
            {
                list = (List<CartItem>)cart;
            }
            return View(list);
        }
        public ActionResult AddItem(long productID, int quanlity)
        {
            var product = new ProductDao().ViewDetail(productID);
            var cart = Session[CartSection];
            if (cart != null)
            {
                var list = (List<CartItem>)cart;
                if (list.Exists(x => x.Product.ID == productID))
                {
                    foreach (var item in list)
                    {
                        if (item.Product.ID == productID)
                        {
                            item.Quantity += quanlity;
                        }
                    }
                }
                else
                {
                    // tạo mới đối tượng cart item
                    var item = new CartItem();
                    item.Product = product;
                    item.Quantity = quanlity;
                    list.Add(item);
                }
                Session[CartSection] = list;
            }
            else
            {
                // tạo mới đối tượng cart item
                var item = new CartItem();
                item.Product = product;
                item.Quantity = quanlity;
                var list = new List<CartItem>();
                list.Add(item);
                // gán  vào sesstion
                Session[CartSection] = list;
            }
            return RedirectToAction("Index");
        }
        public JsonResult Update(string cartModel)
        {
            var jsonCart = new JavaScriptSerializer().Deserialize<List<CartItem>>(cartModel);
            var sessionCart = (List<CartItem>)Session[CartSection];

            foreach (var item in sessionCart)
            {
                var jsonItem = jsonCart.SingleOrDefault(x => x.Product.ID == item.Product.ID);
                if (jsonItem != null)
                {
                    item.Quantity= jsonItem.Quantity;
                }
            }
            Session[CartSection] = sessionCart;
            return Json(new
            {
                status = true
            });
        }
        public JsonResult DeleteAll()
        {
            Session[CartSection] = null;
            return Json(new
            {
                status = true
            });
        }

        public JsonResult Delete(long id)
        {
            var sessionCart = (List<CartItem>)Session[CartSection];
            sessionCart.RemoveAll(x => x.Product.ID == id);
            Session[CartSection] = sessionCart;
            return Json(new
            {
                status = true
            });
        }
        [HttpGet]
        public ActionResult Payment()
        {
            var cart = Session[CartSection];
            var list = new List<CartItem>();
            if (cart != null)
            {
                list = (List<CartItem>)cart;
            }
            return View(list);
        }
        [HttpPost]
        public ActionResult Payment(string shipName, string mobile, string email ,string address)
        {
            var order = new Order();
            order.CreateDate = DateTime.Now;
            order.ShipAddress = address;
            order.ShipMoblie = mobile;
            order.ShipName = shipName;

            try
            {
                var id = new OrderDao().Insert(order);
                var cart = (List<CartItem>)Session[CartSection];
                var detailDao = new Model.Dao.OrderDetailDao();
                decimal total = 0;
                foreach (var item in cart)
                {
                    var orderDetail = new OderDetail();
                    orderDetail.ProductID = item.Product.ID;
                    orderDetail.OrderID = id;
                    orderDetail.Price = item.Product.Price;
                    orderDetail.Quanlity = item.Quantity;
                    detailDao.Insert(orderDetail);


                    total += (item.Product.Price.GetValueOrDefault(0) * item.Quantity);
                }
                string content = System.IO.File.ReadAllText(Server.MapPath("~/assets/client/template/neworder.html"));

                content = content.Replace("{{CustomerName}}", shipName);
                content = content.Replace("{{Phone}}", mobile);
                content = content.Replace("{{Email}}", email);
                content = content.Replace("{{Address}}", address);
                content = content.Replace("{{Total}}", total.ToString("N0"));
                var toEmail = ConfigurationManager.AppSettings["ToEmailAddress"].ToString();

                new MailHelper().SendMail(email, "Đơn hàng mới từ CoffeeMaster", content);
                new MailHelper().SendMail(toEmail, "Đơn hàng mới từ CoffeeMaster", content);
            }
            catch (Exception ex)
            {
                //ghi log
                return Redirect("/loi-thanh-toan");
            }
            return Redirect("/hoan-thanh");
        }
        public ActionResult Success()
        {
            return View();
        }
    }
}

COFFEE/Views/CartItem/Index.cshtml
@model List<COFFEE.Models.CartItem>
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layouts.cshtml";

}

@section jsFooter{

    <script src="../assets/client/js/controller/cartController.js"></script>
}
<div class="container giohang">
    <table id="cart" class="table table-hover table-condensed">
        <thead>
            <tr>
                <th style="width:50%">Tên sản phẩm</th>
                <th style="width:10%">Giá</th>
                <th style="width:10%">Số lượng</th>
                <th style="width:22%" class="text-center">Thành tiền</th>
                <th style="width:10%"> </th>
            </tr>

        </thead>
        @if (Model.Count > 0)
        {
            <tbody>
                @foreach (var item in Model)
                {
                    <tr>
                        <td data-th="Product">
                            <div class="row">
                                <div class="col-sm-2 hidden-xs">
                                    <img src="@item.Product.Image">
                                </div>
                                <div class="col-sm-10 sanpham">
                                    <h4 class="nomargin">@item.Product.Name</h4>
                                    <p>@item.Product.Detail</p>
                                </div>
                            </div>
                        </td>
                        <td data-th="Price">@item.Product.Price.GetValueOrDefault(0).ToString("N0")</td>
                        <td data-th="Quantity">
                            <input class="txtQuantity" data-id="@item.Product.ID" value="@item.Quantity" type="number">
                        </td>
                        <td data-th="Subtotal" class="text-center">@((item.Product.Price.GetValueOrDefault(0) *  item.Quantity).ToString("N0")) </td>
                        <td class="actions" data-th="">

                            <button id="btnUpdate" class="btn btn-info btn-sm">
                                <i class="fas fa-edit"></i>
                            </button>
                            <button id="btn-delete" class="btn btn-danger btn-sm" data-id="@item.Product.ID">
                                <i class="fa fa-trash"></i>
                            </button>
                        </td>


                    </tr>

                }


            </tbody>
        }
        else
        {
            <span class="alert alert">Chưa Có Sản Phẩm Trong Giỏ hàng</span>
        }
        <tfoot>          
        </tfoot>
        <tfoot>
            <tr class="nohover">
                <td>
                    <a href="#" class="btn btn-warning nutbt" id="btnContinue">
                        <i class="fa fa-angle-left"></i>
                        Tiếp tục mua hàng
                    </a>
                    <a href="#" class="btn btn-warning nutbt" id="btnUpdate">
                        <i class="fa fa-angle-left"></i>
                        Cập Nhật
                    </a>
                    <a href="#" class="btn btn-warning nutbt" id="btnDeleteAll">
                        <i class="fa fa-angle-left"></i>
                        Xóa Giỏ Hàng
                    </a>
                    <a href="#" class="btn btn-warning nutbt" id="btnPayment">
                        <i class="fa fa-angle-left"></i>
                        Thanh Toán
                    </a>
                </td>
                <td colspan="2" class="hidden-xs"></td>
                <td class="ghthanhtien">
                    <strong>Tổng tiền <span></span> VNĐ</strong>
                </td>
                <td>
                    <a href="#" class="btn btn-success btn-block nutbt">Thanh toán <i class="fa fa-angle-right"></i></a>
                </td>
            </tr>
        </tfoot>
    </table>

        @*<div class="bottom adjoined-top">
            <button id="btnContinue" class="btn">Tiếp tục mua hàng</button>
            <button id="btnUpdate" class="btn">Cập nhật giỏ hàng</button>
            <button id="btnDeleteAll" class="btn">Xoá giỏ hàng</button>
            <button id="btnPayment" class="btn">Thanh toán</button>
        </div>*@



</div>

COFFEE/Views/CartItem/Payment.cshtml
@model List<COFFEE.Models.CartItem>
@{
    ViewBag.Title = "Thanh toán";
    Layout = "~/Views/Shared/_Layouts.cshtml";
}
<div class="content">
    <div class="section group">
        @if (Model.Count > 0)
        {
            <table class="table">
                <thead>
                    <tr>
                        <td>Mã SP</td>
                        <td>Tên SP</td>
                        <td>Ảnh SP</td>
                        <td>Số lượng</td>
                        <td>Đơn giá</td>
                        <td>Thành tiền</td>
                        <td></td>
                    </tr>
                </thead>
                <tbody>
                    @foreach (var item in Model)
                    {
                        <tr>
                            <td>@item.Product.ID</td>
                            <td>@item.Product.Name</td>
                            <td><img src="@item.Product.Image" width="100" /></td>
                            <td><input type="text" class="txtQuantity" data-id="@item.Product.ID" value="@item.Quantity" /></td>
                            <td>@item.Product.Price.GetValueOrDefault(0).ToString("N0")</td>
                            <td>@((item.Product.Price.GetValueOrDefault(0) * item.Quantity).ToString("N0"))</td>
                            <td><a href="#" data-id="@item.Product.ID" class="btn-delete">Xoá</a></td>
                        </tr>
                    }

                </tbody>
            </table>
        }

    </div>
    <div class="section group">
        <div class="col-md-6">
            @using (Html.BeginForm("Payment", "CartItem", FormMethod.Post))
            {
                <div class="form-group">
                    <label>Người nhận</label>
                    <input name="shipName" class="form-control" />
                </div>
                <div class="form-group">
                    <label>Điện thoại</label>
                    <input name="mobile" class="form-control" />
                </div>
                <div class="form-group">
                    <label>Địa chỉ</label>
                    <input name="address" class="form-control" />
                </div>
                <div class="form-group">
                    <label>Email</label>
                    <input name="email" class="form-control" />
                </div>
                <button type="submit" class="btn">Gửi đơn hàng</button>
            }
        </div>

    </div>
</div>

COFFEE/Views/CartItem/Success.cshtml
@{
    ViewBag.Title = "Success";
    Layout = "~/Views/Shared/_Layouts.cshtml";
}
<div class="content">
    <div class="section group">
        <div class="alert alert-success">
            Bạn vừa mua hàng thành công.
        </div>
    </div>
</div>